dados_policiais/dados_policiais/dados_policiais/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('mainApp.urls')),
    path('', include('pc.urls')),
    path('', include('pcepa.urls')),
    path('admin/', admin.site.urls),
]

dados_policiais/dados_policiais/pc/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('cadastro/acoes/nro_ocorrencia/', views.nro_ocorrencia, name='nro_ocorrencia'),
    path('cadastro/acoes/proced_policial/', views.proced_policial, name='proced_policial'),
    path('registros/ocorrencias/', views.pc_ocorrencias, name='ocorrencias'),
]

dados_policiais/dados_policiais/pc/models.py
from django.db import models
from mainApp.models import *
from mainApp.list_choices import *



# Create your models here.
class ModelBop_Atuacao(models.Model):
    id_atuacao = models.AutoField(primary_key=True, unique=True, db_index=True, serialize=True)
    ds_atuacao = models.CharField(max_length=30, null=True, blank=False,choices=BOP_ATU)
    data_registro = models.DateTimeField(auto_now_add=True)
    data_manutencao = models.DateTimeField(auto_now=True)
    
    class Meta:
        db_table = 'pc_bop_atuacao'
        
class ModelProced_Atuacao(models.Model):
    id_atuacao = models.AutoField(primary_key=True, unique=True, db_index=True, serialize=True)
    ds_atuacao = models.CharField(max_length=30, null=True, blank=False,choices=PROC_ATU)
    data_registro = models.DateTimeField(auto_now_add=True)
    data_manutencao = models.DateTimeField(auto_now=True)
    
    class Meta:
        db_table = 'pc_procedimento_atuacao'
        
class ModelBop(models.Model):
    nro_bop = models.CharField(max_length=100, primary_key=True, null=False, blank=False)
    data_registro = models.DateTimeField(auto_now_add=True)
    data_manutencao = models.DateTimeField(auto_now=True)
    apresentacao = models.BooleanField(null=False)
    cumprimento_medidas = models.BooleanField(null=False)
    instituicao = models.CharField(max_length=10, null=True, blank=False,choices=INST)
    processo = models.CharField(max_length=100,null=True,blank=False)
    enquadramento = models.CharField(max_length=200, null=False, blank=False)
    fato_relevante = models.BooleanField(null=False)
    # id_relator = models.ForeignKey(ModelPessoas, db_column='id_relator',related_name='id_relator',on_delete=models.CASCADE)
    # id_suspeito = models.ForeignKey(ModelPessoas, db_column='id_suspeito',related_name='id_suspeito',on_delete=models.CASCADE)
    id_usuario = models.ForeignKey(ModelUsuarios, db_column='id_usuario',related_name='id_usuario_pc_ocor',on_delete=models.CASCADE)
    id_comandante = models.ForeignKey(ModelUsuarios, db_column='id_comandante',related_name='id_comandante_pc_ocor', on_delete=models.CASCADE)
    id_operacao = models.ForeignKey(ModelOperacoes, db_column='id_operacao',related_name='id_operacao_pc_ocor', on_delete=models.CASCADE)
    
    class Meta:
        db_table = 'pc_bop'


class ModelProcedimento(models.Model):
    nro_procedimento = models.CharField(max_length=100, primary_key=True, null=False, blank=False)
    data_registro = models.DateTimeField(auto_now_add=True)
    data_manutencao = models.DateTimeField(auto_now=True)
    enquadramento = models.CharField(max_length=200, null=False, blank=False)
    id_usuario = models.ForeignKey(ModelUsuarios, db_column='id_usuario',related_name='id_usuario_pc_proced',on_delete=models.CASCADE)
    id_comandante = models.ForeignKey(ModelUsuarios, db_column='id_comandante',related_name='id_comandante_pc_proced', on_delete=models.CASCADE)
    id_operacao = models.ForeignKey(ModelOperacoes, db_column='id_operacao',related_name='id_operacao_pc_proced', on_delete=models.CASCADE)
    
    class Meta:
        db_table = 'pc_procedimentos'

class ModelBop_Procedimento(models.Model):
    nro_bop = models.ForeignKey(ModelBop,db_column='nro_bop',related_name='nro_bop_pc_proced', on_delete=models.CASCADE)
    nro_procedimento = models.ForeignKey(ModelProcedimento,db_column='nro_procedimento',related_name='nro_procedimento_pc_proced', on_delete=models.CASCADE)
    
    class Meta:
        db_table = 'pc_bop_proc'

class ModelBop_Pessoa(models.Model):
    id_atuacao = models.ForeignKey(ModelBop_Atuacao,db_column='id_atuacao',related_name='id_atuacao_pc_bp', on_delete=models.CASCADE)
    id_pessoa = models.ForeignKey(ModelPessoas,db_column='id_pessoa',related_name='id_pessoa_pc_bp', on_delete=models.CASCADE)
    nro_bop = models.ForeignKey(ModelBop,db_column='nro_bop',related_name='nro_bop_pc_bp', on_delete=models.CASCADE)
    
    class Meta:
        db_table = 'pc_bop_pessoa'
        
class ModelProc_Pessoa(models.Model):
    id_atuacao = models.ForeignKey(ModelProced_Atuacao,db_column='id_atuacao',related_name='id_atuacao_pc_pp', on_delete=models.CASCADE)
    id_pessoa = models.ForeignKey(ModelPessoas,db_column='id_pessoa',related_name='id_pessoa_pc_pp', on_delete=models.CASCADE)
    nro_procedimento = models.ForeignKey(ModelProcedimento,db_column='nro_procedimento',related_name='nro_procedimento_pc_pp', on_delete=models.CASCADE)
    
    class Meta:
        db_table = 'pc_procedimento_pessoa'

class ModelApreensao(models.Model):
    id_apreensao = models.AutoField(primary_key=True, unique=True, db_index=True, serialize=True)
    endereco = models.CharField(max_length=200, null=False, blank=False)
    data_apreensao = models.DateField(null=False, blank=False)
    objeto_apreendido = models.CharField(max_length=200, choices=CLASS_OBJ)
    tipo_objeto = models.CharField(max_length=200)
    especie_modelo = models.CharField(max_length=200)
    nro_identificador = models.CharField(max_length=200)
    tipo_nro_identificador = models.CharField(max_length=200)
    nro_identificador2 = models.CharField(max_length=200)
    tipo_nro_identificador2 = models.CharField(max_length=200)
    qtd = models.FloatField(null=False, blank=False)
    und_medida = models.CharField(max_length=200, choices=UNIDADE_MEDIDA)
    
    class Meta:
        db_table = 'pc_apreensao'

class ModelBop_Apreensao(models.Model):
    nro_bop = models.ForeignKey(ModelBop,db_column='nro_bop',related_name='nro_bop_apreensao', on_delete=models.CASCADE,null=True)
    id_apreensao = models.ForeignKey(ModelApreensao,db_column='id_apreensao',related_name='id_apreensao_apreensao', on_delete=models.CASCADE,null=True) #foreignkey ocorrencia
    
    class Meta:
        db_table = 'pc_bop_apreensao'
        
class ModelCumprimentoMedidas(models.Model):
    nro_bop = models.ForeignKey(ModelBop,db_column='nro_bop',related_name='nro_bop_pc_CM', on_delete=models.CASCADE)
    processo = models.CharField(max_length=100,null=False,blank=False)
    enquadramento = models.CharField(max_length=200, null=False, blank=False)
    instituicao = models.CharField(max_length=10, null=False, blank=False,choices=INST)
    data_registro = models.DateTimeField(auto_now_add=True)
    data_manutencao = models.DateTimeField(auto_now=True)
    fato_relevante = models.BooleanField(null=False)
    id_usuario = models.ForeignKey(ModelUsuarios, db_column='id_usuario',related_name='id_usuario_pc_cump',on_delete=models.CASCADE)
    id_operacao = models.ForeignKey(ModelOperacoes, db_column='id_operacao',related_name='id_operacao_pc_cump', on_delete=models.CASCADE)
    
    class Meta:
        db_table = 'pc_cumprimento_medidas'

dados_policiais/dados_policiais/pc/views.py
att_joao
import json
from django.core.serializers.json import DjangoJSONEncoder
from time import sleep
from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger
from django.db import IntegrityError
from django.db.models import Sum,Q
from django.http import HttpResponse, QueryDict
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from mainApp.views import *
from django.contrib.auth.models import User
from mainApp.models import *
from .models import *
import datetime
from .form import *
from mainApp.form import *


@login_required
def nro_ocorrencia(request):
    template = 'nro_ocorrencia.html'
    if request.method == 'GET' and ModelUsuarios.objects.get(id=request.user.id).instituicao == 'PC':
        form_ocorrencia = OcorrenciasForm()
        form_apreensao = ApreensaoForm(prefix='apreensao1')
        form_pessoas = PessoasForm(prefix='pessoa1')
        operacoes, chefes, instituicao = base(request)
        context = {'operacoes':operacoes,
                'chefes': chefes,
                'instituicao': instituicao,
                'form_pessoa': form_pessoas,
                'form_ocorrencia': form_ocorrencia,
                'form_apreensao': form_apreensao,
                }
        return render(request, template,context)
    elif request.POST:
        form_ocorrencia = OcorrenciasForm(request.POST)
        if request.POST.get('nro_bop'):
            try:
                ModelBop.objects.get(nro_bop=request.POST.get('nro_bop'))
                return HttpResponse('Esse numero de ocorrencia ja esta cadastrado')
            except: pass
            bop_apreensao = []
            if form_ocorrencia.is_valid():
                ocorrencia = ModelBop(nro_bop=request.POST.get('nro_bop'),apresentacao='True' if request.POST.get('apresentacao') else 'False',fato_relevante='True' if request.POST.get('fato_relevante') else 'False',enquadramento=request.POST.get('enquadramento'),id_usuario=ModelUsuarios.objects.get(id=request.user.id),id_operacao=ModelOperacoes.objects.get(id=request.POST.get('nome_op')),id_comandante=ModelUsuarios.objects.get(id=request.POST.get('chefe_guarnicao')),cumprimento_medidas='True' if request.POST.get('cumprimento_medidas') else 'False',instituicao=request.POST.get('instituicao') if request.POST.get('instituicao') else None,processo=request.POST.get('processo') if request.POST.get('processo') else None)
                ocorrencia.save()
                try:
                    for prefix in range(1,int(request.POST.get('qtd_apreensao'))+1):
                        apreensao = ApreensaoForm(request.POST,prefix=f'apreensao{prefix}')
                        if apreensao.is_valid():
                            apreensao = apreensao.save()
                            bop_ap = ModelBop_Apreensao(nro_bop=ocorrencia,id_apreensao=apreensao)
                            bop_ap.save()
                            bop_apreensao.append(model_to_dict(apreensao))
                except IntegrityError:
                    pass
                
                pessoas = save_pessoas(request,ModelBop_Pessoa, ocorrencia)
                context = {
                    'registro':model_to_dict(ocorrencia),
                    'registro_pessoas':pessoas,
                    'registro_item':bop_apreensao,
                    'instituicao': ModelUsuarios.objects.get(id=request.user.id).instituicao,
                }
                context_json = json.dumps(context, cls=DjangoJSONEncoder)
                request.session['context'] = context_json
                return redirect('extrato')
            else:
                return HttpResponse('nao salvo')
    else: return render(request, '404.html')

@login_required
def proced_policial(request):
    # try:
        template = 'proced_policial.html'
        if request.method == 'GET' and ModelUsuarios.objects.get(id=request.user.id).instituicao == 'PC':
            form_proc = ProcedimentoForm()
            bop_proc = BopProcForm()
            form_pessoas = PessoasForm(prefix='pessoa1')
            operacoes, chefes, instituicao = base(request)
            context = {'operacoes':operacoes,
                        'chefes': chefes,
                        'instituicao': instituicao,
                        'form_pessoa': form_pessoas,
                        'form_proc': form_proc,
                        'bop_proc': bop_proc,
                        }
            return render(request, template,context)
        elif request.POST:
            form_procedimento = ProcedimentoForm(request.POST)
            form_bopproc = BopProcForm(request.POST)
            try:
                ocorrencia = ModelBop.objects.get(nro_bop=request.POST.get('nro_bop'))
            except: 
                return HttpResponse('Esse Boletim nao existe no banco de dados. portanto nao pode ser associado a um procedimento')
            try:
                proced = ModelProcedimento.objects.get(nro_procedimento=request.POST.get('nro_procedimento'))
            except: 
                proced = None
            try:
                bop_proc = ModelBop_Procedimento.objects.get(nro_bop=ocorrencia,nro_procedimento=proced)
                return HttpResponse('Esse Boletim ja esta vinculado a esse procedimento')
            except:
                pass
            if form_procedimento.is_valid():
                if proced:
                    bop_proc = ModelBop_Procedimento(nro_bop=ocorrencia,nro_procedimento=proced)
                    bop_proc.save()
                else:
                    proced = ModelProcedimento(nro_procedimento=request.POST.get('nro_procedimento'),enquadramento=request.POST.get('enquadramento'),id_usuario=ModelUsuarios.objects.get(id=request.user.id),id_operacao=ModelOperacoes.objects.get(id=request.POST.get('nome_op')),id_comandante=ModelUsuarios.objects.get(id=request.POST.get('chefe_guarnicao')),data_registro=datetime.datetime.now())
                    proced.save()
                    bop_proc = ModelBop_Procedimento(nro_bop=ocorrencia,nro_procedimento=proced)
                    bop_proc.save()    
                pessoas = save_pessoas(request,ModelProc_Pessoa, proced)
                context = {
                        'registro':model_to_dict(ocorrencia),
                        'registro_pessoas':pessoas,
                        'registro_item':model_to_dict(proced),
                        'instituicao': ModelUsuarios.objects.get(id=request.user.id).instituicao,
                    }
                print(model_to_dict(proced))
                context_json = json.dumps(context, cls=DjangoJSONEncoder)
                request.session['context'] = context_json
                return redirect('extrato')
            else:
                return HttpResponse('nao salvo')
        else: return render(request, '404.html')
    
@login_required
def pc_ocorrencias(request):
    usuario = request.user
    instituicao = ModelUsuarios.objects.get(id=usuario.id).instituicao
    parametro_page = request.GET.get('page','1')
    parametro_limit = request.GET.get('limit','15')
    if not(parametro_limit.isdigit() and int(parametro_limit)>0):
        parametro_limit = '15'
    
    Registros = ModelBop.objects.filter(id_usuario=request.user.id).order_by('-data_registro')
    busca = request.GET.get('busca')
    if busca:
        Registros = ModelBop.objects.filter(Q(nro_bop__icontains=busca)|Q(enquadramento__icontains=busca)).order_by('-data_registro')
    else:
        Registros = ModelBop.objects.filter(id_usuario=request.user.id).order_by('-data_registro')
    ocorrencias_paginator = Paginator(Registros,parametro_limit)
    try:
        page = ocorrencias_paginator.page(parametro_page)
    except (EmptyPage, PageNotAnInteger):
        page = ocorrencias_paginator.page(1)
    operacoes = ModelOperacoes.objects.all()
    pessoa = ModelPessoas.objects.all()
    chefes = ModelUsuarios.objects.filter(comandante='True')
    context = {
        'quantidade_por_pagina': ['10','15','25','50','100'],
        'limitp': parametro_limit,
        "instituicao":instituicao,
        'registro': page,
        'operacao': operacoes,
        'chefes':chefes,
        'pessoa':pessoa,
    }
    return render(request, 'registro_acoes_pc.html',context)

dados_policiais/dados_policiais/pc/templates/nro_ocorrencia.html
{% extends "extends/cadastro_base.html" %}
{% load static %}

{% block title %}Número de Ocorência{% endblock %}
{% block nav_title %}Número de Ocorrência{% endblock %}

{% block campos %}
    <div class="col-12 col-md-6 pb-5">
        <div class="form-control m-auto mt-4">
            <div class="row">
                <div class="col-12 col-lg-4">
                    <div class="form-check form-switch">
                        <input  class="form-check-input mt-2" type="checkbox" name="apresentacao" id="apresentacao">
                        <label class="ms-1 fs-5 w-md-100" for="apresentacao">Apresentação</label>
                    </div>
                    <div class="form-check form-switch">
                        <input  class="form-check-input mt-2" type="checkbox" name="fato_relevante" id="fato_relevante">
                        <label class="ms-1 fs-5 w-md-100" for="fato_relevante">Fato relevante</label>
                    </div>
                </div>
                <div class="col-12 col-lg-8">
                    <div class="form-check form-switch">
                        <input  class="form-check-input mt-2" type="checkbox" onclick="mostrarCumprimento(this)" name="cumprimento_medidas" id="cumprimento_medidas" >
                        <label class="ms-1 fs-5 w-md-100" for="cumprimento_medidas">Cumprimento de medidas</label>
                    </div>
                    <div class="form-check form-switch">
                        <input  class="form-check-input mt-2" type="checkbox" onclick="mostrarApreensao(this)" name="cumprimento_medidas" id="cumprimento_medidas" >
                        <label class="ms-1 fs-5 w-md-100" for="cumprimento_medidas">Apreensão</label>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <label class="fs-5 mt-3" for="nro_bop">Nº. do BOP:</label>
                <input required class="form-control" type="text" name="nro_bop" id="nro_bop" value="{{form_ocorrencia.nro_bop.value|default_if_none:''}}" mask="bop" maxlength="19" placeholder="00000/0000.000000-0">
                
                <label class="fs-5 mt-3" for="enquadramento">Enquadramento:</label>
                <input required class="form-control" type="text" name="enquadramento" id="enquadramento" value="{{form_ocorrencia.enquadramento.value|default_if_none:''}}">
            </div>
            <div class="col-12 col-md-6" id="camposCumprimentoMedidas">
                <label class="fs-5 mt-3" for="processo">Processo:</label>
                <input  class="form-control" type="text" name="processo" id="processo" value="{{form_ocorrencia.processo.value|default_if_none:''}}">
                
                <label class="fs-5 mt-3 w-100" for="instituicao">Orgão responsavel:</label>
                <select class="form-control" name="instituicao" id="id_instituicao">
                    <option value="{{form_ocorrencia.instituicao.value|default_if_none:''}}" selected="">{{form_ocorrencia.instituicao.value|default_if_none:''}}</option>
                    <option value="PM">PM</option>
                    <option value="PC">PC</option>
                    <option value="PC/PM">PC/PM</option>
                </select>
            </div>
        </div>
        <div class="row">
            <div class="col-12 mt-4">
                {% include 'includes/add_itens.html' with type='Envolvidos'%}
            </div>
            <div id="camposApreensao" class="col-12 mt-4">
                {% include 'includes/add_itens.html' with type='Apreensao'%}
            </div>
        </div>
        


        {% include 'includes/operacao.html' %}
        {% include 'includes/pesquisa.html' %}        
    </div>
</div>
{% endblock %}

dados_policiais/dados_policiais/pc/templates/proced_policial.html
{% extends "extends/cadastro_base.html" %}
{% load static %}

{% block title %}Procedimento Policial{% endblock %}
{% block nav_title %}Procedimento Policial{% endblock %}

{% block campos %}
    <div class="col-12 col-md-6 pb-5">
        <label class="fs-5 mt-3" for="nro_bop">Nº. do BOP:</label>
        
        <p style='color: red'> adicionar pesquisa do bop e renderizar dados do bop</p>
        <input required class="form-control" type="text" name="nro_bop" id="nro_bop" value='{{form_bopproc.nro_bop.value|default_if_none:''}}' mask="bop" maxlength="19" placeholder="xxxxx/xxxx.xxxxxx-x">

        <label class="fs-5 mt-3" for="nro_procedimento">Nº. Procedimento:</label>
        
        <input required class="form-control" type="text" name="nro_procedimento" id="nro_procedimento" value='{{form_bopproc.nro_procedimento.value|default_if_none:''}}' mask="bop" maxlength="19" placeholder="xxxxx/xxxx.xxxxxx-x"> 
        
        <label class="fs-5 mt-3" for="enquadramento">Enquadramento:</label>
        
        <input required class="form-control" type="text" name="enquadramento" id="enquadramento" value='{{form_procedimento.enquadramento.value|default_if_none:''}}'>
        
        <div class="row">
            <div class="col-12 mt-4">
                {% include 'includes/add_itens.html' with type='Envolvidos'%}
            </div>
        </div>
    {% include 'includes/operacao.html' %}
    {% include 'includes/pesquisa.html' %}
{% endblock %}

dados_policiais/dados_policiais/pc/templates/registro_acoes_pc.html
{% extends "extends/base.html" %}
{% load static %}


{% block css%}
<link rel="stylesheet" href="{% static 'css/registros.css' %}">
{% endblock %}
{% block js%}{% endblock %}
{% block title %}Página Inicial{% endblock %}


{% block content %}
{% include "includes/header.html" with nav_title="Lista de registros" back=True %}
<main class="container">
    <div class="row pt-4">
        <table class="table table-striped" id="tabela_registros">
            <thead>
              <tr>
                <th scope="col">Nr bop</th>
                <th scope="col">Data registro</th>
                <th scope="col">Apresentacao</th>
                <th scope="col">Enquadramento</th>
                <th scope="col">Relator</th>
                <th scope="col">Suspeito</th>
                <th scope="col">Chefe guarnição</th>
                <th scope="col">Operação</th>
              </tr>
            </thead>
            <tbody>
                {% for ocorrencia in registro%}
                    <tr onclick="window.location.href='{{ocorrencia.nro_bop}}/'">
                        {% comment %} <td><a href="{% url 'update' ocorrencia.nro_registro%}">{{ocorrencia.nro_registro}}</a></td> {% endcomment %}
                        <td min-width="250px">{{ocorrencia.nro_bop}}</td>
                        <td>{{ocorrencia.data_registro|date:'d/m/Y'}}</td>
                        {% if ocorrencia.apresentacao %}
                            <td><input type="checkbox" name="" id="" checked disabled></td>
                        {% else %}
                        <td><input type="checkbox" name="" id="" disabled></td>
                        {%endif%}
                        <td>{{ocorrencia.enquadramento}}</td>
                        {% if ocorrencia.id_relator %}
                            {% for p in pessoa %}
                                {% if p.id_pessoa == ocorrencia.id_relator.id_pessoa %}
                                    <td min-width="250px">{{p.nome_completo}}</td>
                                {% endif %}
                            {% endfor %}
                        {% endif %}
                        {% if ocorrencia.id_suspeito %}
                            {% for p in pessoa %}
                                {% if p.id_pessoa == ocorrencia.id_suspeito.id_pessoa %}
                                    <td min-width="250px">{{p.nome_completo}}</td>
                                {% endif %}
                            {% endfor %}
                        {% endif %}
                         {% if ocorrencia.id_comandante %}
                            {% for chefe in chefes%}
                                {% if chefe.id == ocorrencia.id_comandante.id %}
                                    <td min-width="250px">{{chefe.nome_completo}}</td>
                                {% endif %}
                            {% endfor %}
                        {% endif %}
                        {% if ocorrencia.id_operacao %}
                            {% for operacao in operacao%}
                                {% if operacao.id == ocorrencia.id_operacao.id %}
                                    <td>{{operacao.nome_operacao}}</td>
                                {% endif %}
                            {% endfor %}
                        {% endif %}
                        <td class="icon">
                            <a href="*"><i class="fa-solid fa-trash" ></i></a>
                        </td>
                    </tr>
                {%endfor%}
            </tbody>
        </table>
    </div>
</main>
{% endblock %}