dados_policiais/dados_policiais/dados_policiais/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('mainApp.urls')),
    path('', include('pc.urls')),
    path('', include('pcepa.urls')),
    path('admin/', admin.site.urls),
]

dados_policiais/dados_policiais/pc/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('cadastro/acoes/nro_ocorrencia/', views.nro_ocorrencia, name='nro_ocorrencia'),
    path('cadastro/acoes/proced_policial/', views.proced_policial, name='proced_policial'),
    path('registros/ocorrencias/', views.pc_ocorrencias, name='ocorrencias'),
]

dados_policiais/dados_policiais/pc/models.py
from django.db import models
from mainApp.models import *
from mainApp.list_choices import *



# Create your models here.
class ModelBop_Atuacao(models.Model):
    id_atuacao = models.AutoField(primary_key=True, unique=True, db_index=True, serialize=True)
    ds_atuacao = models.CharField(max_length=30, null=True, blank=False,choices=BOP_ATU)
    data_registro = models.DateTimeField(auto_now_add=True)
    data_manutencao = models.DateTimeField(auto_now=True)
    
    class Meta:
        db_table = 'pc_bop_atuacao'
        
class ModelProced_Atuacao(models.Model):
    id_atuacao = models.AutoField(primary_key=True, unique=True, db_index=True, serialize=True)
    ds_atuacao = models.CharField(max_length=30, null=True, blank=False,choices=PROC_ATU)
    data_registro = models.DateTimeField(auto_now_add=True)
    data_manutencao = models.DateTimeField(auto_now=True)
    
    class Meta:
        db_table = 'pc_procedimento_atuacao'
        
class ModelBop(models.Model):
    nro_bop = models.CharField(max_length=100, primary_key=True, null=False, blank=False)
    data_registro = models.DateTimeField(auto_now_add=True)
    data_manutencao = models.DateTimeField(auto_now=True)
    apresentacao = models.BooleanField(null=False)
    cumprimento_medidas = models.BooleanField(null=False)
    instituicao = models.CharField(max_length=10, null=True, blank=False,choices=INST)
    processo = models.CharField(max_length=100,null=True,blank=False)
    enquadramento = models.CharField(max_length=200, null=False, blank=False)
    fato_relevante = models.BooleanField(null=False)
    # id_relator = models.ForeignKey(ModelPessoas, db_column='id_relator',related_name='id_relator',on_delete=models.CASCADE)
    # id_suspeito = models.ForeignKey(ModelPessoas, db_column='id_suspeito',related_name='id_suspeito',on_delete=models.CASCADE)
    id_usuario = models.ForeignKey(ModelUsuarios, db_column='id_usuario',related_name='id_usuario_pc_ocor',on_delete=models.CASCADE)
    id_comandante = models.ForeignKey(ModelUsuarios, db_column='id_comandante',related_name='id_comandante_pc_ocor', on_delete=models.CASCADE)
    id_operacao = models.ForeignKey(ModelOperacoes, db_column='id_operacao',related_name='id_operacao_pc_ocor', on_delete=models.CASCADE)
    
    class Meta:
        db_table = 'pc_bop'


class ModelProcedimento(models.Model):
    nro_procedimento = models.CharField(max_length=100, primary_key=True, null=False, blank=False)
    data_registro = models.DateTimeField(auto_now_add=True)
    data_manutencao = models.DateTimeField(auto_now=True)
    enquadramento = models.CharField(max_length=200, null=False, blank=False)
    id_usuario = models.ForeignKey(ModelUsuarios, db_column='id_usuario',related_name='id_usuario_pc_proced',on_delete=models.CASCADE)
    id_comandante = models.ForeignKey(ModelUsuarios, db_column='id_comandante',related_name='id_comandante_pc_proced', on_delete=models.CASCADE)
    id_operacao = models.ForeignKey(ModelOperacoes, db_column='id_operacao',related_name='id_operacao_pc_proced', on_delete=models.CASCADE)
    
    class Meta:
        db_table = 'pc_procedimentos'

class ModelBop_Procedimento(models.Model):
    nro_bop = models.ForeignKey(ModelBop,db_column='nro_bop',related_name='nro_bop_pc_proced', on_delete=models.CASCADE)
    nro_procedimento = models.ForeignKey(ModelProcedimento,db_column='nro_procedimento',related_name='nro_procedimento_pc_proced', on_delete=models.CASCADE)
    
    class Meta:
        db_table = 'pc_bop_proc'

class ModelBop_Pessoa(models.Model):
    id_atuacao = models.ForeignKey(ModelBop_Atuacao,db_column='id_atuacao',related_name='id_atuacao_pc_bp', on_delete=models.CASCADE)
    id_pessoa = models.ForeignKey(ModelPessoas,db_column='id_pessoa',related_name='id_pessoa_pc_bp', on_delete=models.CASCADE)
    nro_bop = models.ForeignKey(ModelBop,db_column='nro_bop',related_name='nro_bop_pc_bp', on_delete=models.CASCADE)
    
    class Meta:
        db_table = 'pc_bop_pessoa'
        
class ModelProc_Pessoa(models.Model):
    id_atuacao = models.ForeignKey(ModelProced_Atuacao,db_column='id_atuacao',related_name='id_atuacao_pc_pp', on_delete=models.CASCADE)
    id_pessoa = models.ForeignKey(ModelPessoas,db_column='id_pessoa',related_name='id_pessoa_pc_pp', on_delete=models.CASCADE)
    nro_procedimento = models.ForeignKey(ModelProcedimento,db_column='nro_procedimento',related_name='nro_procedimento_pc_pp', on_delete=models.CASCADE)
    
    class Meta:
        db_table = 'pc_procedimento_pessoa'

class ModelApreensao(models.Model):
    id_apreensao = models.AutoField(primary_key=True, unique=True, db_index=True, serialize=True)
    endereco = models.CharField(max_length=200, null=False, blank=False)
    data_apreensao = models.DateField(null=False, blank=False)
    objeto_apreendido = models.CharField(max_length=200, choices=CLASS_OBJ)
    tipo_objeto = models.CharField(max_length=200)
    especie_modelo = models.CharField(max_length=200)
    nro_identificador = models.CharField(max_length=200)
    tipo_nro_identificador = models.CharField(max_length=200)
    nro_identificador2 = models.CharField(max_length=200)
    tipo_nro_identificador2 = models.CharField(max_length=200)
    qtd = models.FloatField(null=False, blank=False)
    und_medida = models.CharField(max_length=200, choices=UNIDADE_MEDIDA)
    
    class Meta:
        db_table = 'pc_apreensao'

class ModelBop_Apreensao(models.Model):
    nro_bop = models.ForeignKey(ModelBop,db_column='nro_bop',related_name='nro_bop_apreensao', on_delete=models.CASCADE,null=True)
    id_apreensao = models.ForeignKey(ModelApreensao,db_column='id_apreensao',related_name='id_apreensao_apreensao', on_delete=models.CASCADE,null=True) #foreignkey ocorrencia
    
    class Meta:
        db_table = 'pc_bop_apreensao'
        
class ModelCumprimentoMedidas(models.Model):
    nro_bop = models.ForeignKey(ModelBop,db_column='nro_bop',related_name='nro_bop_pc_CM', on_delete=models.CASCADE)
    processo = models.CharField(max_length=100,null=False,blank=False)
    enquadramento = models.CharField(max_length=200, null=False, blank=False)
    instituicao = models.CharField(max_length=10, null=False, blank=False,choices=INST)
    data_registro = models.DateTimeField(auto_now_add=True)
    data_manutencao = models.DateTimeField(auto_now=True)
    fato_relevante = models.BooleanField(null=False)
    id_usuario = models.ForeignKey(ModelUsuarios, db_column='id_usuario',related_name='id_usuario_pc_cump',on_delete=models.CASCADE)
    id_operacao = models.ForeignKey(ModelOperacoes, db_column='id_operacao',related_name='id_operacao_pc_cump', on_delete=models.CASCADE)
    
    class Meta:
        db_table = 'pc_cumprimento_medidas'

dados_policiais/dados_policiais/pcepa/models.py
from django.db import models
from mainApp.models import *
from pc.models import *
# Create your models here.
# alterar


class ModelRegistrospcepa(models.Model):
    protocolo = models.CharField(primary_key=True,max_length=30,null=False,blank=False)
    caso = models.CharField(max_length=50,null=False,blank=False)
    bop_tombo = models.CharField(max_length=100,null=False,blank=False)
    tipo_exame = models.CharField(max_length=100,null=False,blank=False)
    data_exame = models.DateTimeField(auto_now=False, auto_now_add=False)
    data_registro = models.DateTimeField(auto_now_add=True)
    data_manutencao = models.DateTimeField(auto_now=True)
    id_usuario = models.ForeignKey(ModelUsuarios, db_column='id_usuario',related_name='id_usuario_pcepa',on_delete=models.CASCADE)
    id_operacao = models.ForeignKey(ModelOperacoes, db_column='id_operacao',related_name='id_operacao_pcepa', on_delete=models.CASCADE)
    id_comandante = models.ForeignKey(ModelUsuarios, db_column='id_comandante',related_name='id_comandante_pcepa', on_delete=models.CASCADE)
    
    class Meta:
        db_table = 'pcepa_registros'
    
class ModelAnaliseDrogapcepa(models.Model):
    protocolo = models.ForeignKey(ModelRegistrospcepa, db_column='protocolo',related_name='protocolo_droga_pcepa', on_delete=models.CASCADE)
    tipo_droga = models.CharField(max_length=100,null=False,blank=False,choices=TP_DROGA)
    apresentacao = models.BooleanField(null=True,blank=False)
    qtd = models.FloatField(null=False,blank=False)
    und_medida = models.CharField(max_length=20,null=False,blank=False,choices=UNIDADE_MEDIDA)
    id_imagem = models.ForeignKey(ModelImagens, db_column='id_imagem', on_delete=models.CASCADE,null=True,blank=False, default=None)
    
    class Meta:
        db_table = 'pcepa_analise_droga'
    
    
class ModelAnaliseBalisticapcepa(models.Model):
    protocolo = models.ForeignKey(ModelRegistrospcepa, db_column='protocolo',related_name='protocolo_balistica_pcepa', on_delete=models.CASCADE)
    tipo_material = models.CharField(max_length=100,null=False,blank=False)
    calibre = models.CharField(max_length=20,null=False,blank=False)
    nro_serie_rastreio = models.CharField(max_length=50,null=False,blank=False)
    nro_patrimonio = models.CharField(max_length=50,null=True,blank=False)
    qtd = models.IntegerField(null=False,blank=False)
    
    class Meta:
        db_table = 'pcepa_analise_balistica'
    
class ModelPericiaVeicularpcepa(models.Model):
    protocolo = models.ForeignKey(ModelRegistrospcepa, db_column='protocolo',related_name='protocolo_veiculo_pcepa', on_delete=models.CASCADE)
    id_veiculo = models.ForeignKey(ModelVeiculos, db_column='id_veiculo',related_name='id_veiculo_pcepa', on_delete=models.CASCADE)
    
    class Meta:
        db_table = 'pcepa_pericia_veicular'
    
class ModelLesaoCorporalpcepa(models.Model):
    protocolo = models.ForeignKey(ModelRegistrospcepa, db_column='protocolo',related_name='protocolo_lesao_pcepa', on_delete=models.CASCADE)
    id_pessoa = models.ForeignKey(ModelPessoas, db_column='id_pessoa',related_name='id_pessoa_lesao_pcepa', on_delete=models.CASCADE)
        
    class Meta:
        db_table = 'pcepa_lesao_corporal'
    
class ModelLocalCrimepcepa(models.Model):
    protocolo = models.ForeignKey(ModelRegistrospcepa, db_column='protocolo',related_name='protocolo_local_pcepa', on_delete=models.CASCADE)
    latitude = models.CharField(max_length=100,null=False,blank=False)
    longitude = models.CharField(max_length=100,null=False,blank=False)
    preservacao_local = models.CharField(max_length=100,null=False,blank=False)
    vestigios_coletados = models.CharField(max_length=100,null=False,blank=False)
    nro_doc_identficacao = models.CharField(max_length=100,null=False,blank=False)

    
    class Meta:
        db_table = 'pcepa_local_crime'
    
class ModelNecropsiaRemocaopcepa(models.Model):
    protocolo = models.ForeignKey(ModelRegistrospcepa, db_column='protocolo',related_name='protocolo_necropsia_pcepa', on_delete=models.CASCADE)
    nro_doc_identficacao = models.CharField(max_length=100,null=False,blank=False)
    causa_provavel_morte = models.CharField(max_length=100,null=False,blank=False)
    
    class Meta:
        db_table = 'pcepa_necropsia_remocao'
    
    
class ModelRegistrosPessoaspcepa(models.Model):
    protocolo = models.ForeignKey(ModelRegistrospcepa, db_column='protocolo',related_name='protocolo_pessosas_pcepa', on_delete=models.CASCADE)
    id_pessoa = models.ForeignKey(ModelPessoas, db_column='id_pessoa',related_name='id_pessoa_pcepa',on_delete=models.CASCADE)
    
    class Meta:
        db_table = 'pcepa_registros_pessoas'
        
class ModelRegistrosImagens(models.Model):
    protocolo = models.ForeignKey(ModelRegistrospcepa, db_column='protocolo',related_name='protocolo_imagem_pcepa', on_delete=models.CASCADE)
    id_imagem = models.ForeignKey(ModelImagens, db_column='id_imagem',related_name='id_imagem_pcepa',on_delete=models.CASCADE)
    
    class Meta:
        db_table = 'pcepa_registros_imagens'

dados_policiais/dados_policiais/pc/templates/includes/apreensao.html
{% load static%}
<div class="mt-3">  
    <span class="mt-4 fs-5">Apreensão:</span> 
    <div class="form-control m-auto">
        <label for="id_endereco">Endereco:</label>
        <input class="form-control" type="text" name="endereco" maxlength="200"  id="id_endereco">

        <label for="id_tipo_objeto">Tipo objeto:</label>
        <select class="form-select" name="tipo_objeto"  id="id_tipo_objeto">
            <option value="" selected="">---------</option>
            <option value="DOCUMENTO">DOCUMENTO</option>
            <option value="CELULAR">CELULAR</option>
            <option value="OUTRO">OUTRO OBJETO</option>
            <option value="ARMA">ARMA</option>
            <option value="MUNICAO">MUNICAO</option>
            <option value="DROGA">DROGA</option>
            <option value="RECURSO_NATURAL">RECURSO NATURAL</option>
            <option value="PARTES_DO_CORPO">PARTES DO CORPO</option>
            <option value="VEICULO">VEICULO</option>
        </select>
        <span class="mt-4 fs-5">Droga:</span> 
        <div class="form-control m-auto">
            <label for="id_tipo_droga">Tipo droga:</label>
            <select class="form-select" name="tipo_droga"  id="id_tipo_droga">
                <option value="" selected="">---------</option>
                <option value="ANFETAMINA">ANFETAMINA</option>
                <option value="COCAINA">COCAINA</option>
                <option value="CRACK">CRACK</option>
                <option value="ECSTASY">ECSTASY</option>
                <option value="MACONHA">MACONHA</option>
                <option value="MDMA">MDMA</option>
                <option value="MERLA">MERLA</option>
                <option value="NOBESIO">NOBESIO</option>
                <option value="OXI">OXI</option>
            </select>

            <label for="id_qtd_droga">Qtd droga:</label>
            <input class="form-control" type="number" name="qtd_droga" step="any"  id="id_qtd_droga">

            <label for="id_und_medida">Und medida:</label>  
            <select class="form-select" name="und_medida"  id="id_und_medida">
                <option value="" selected="">---------</option>
                <option value="Kg">QUILOGRAMA</option>
                <option value="g">GRAMAS</option>
                <option value="UND">UNIDADE</option>
                <option value="L">LITROS</option>
            </select>
        </div>
        <span class="mt-4 fs-5">Arma:</span> 
        <div class="form-control m-auto">
            <label for="id_tipo_arma">Tipo arma:</label>
            <select class="form-select" name="tipo_arma"  id="id_tipo_arma">
                <option value="" selected="">---------</option>
                <option value="ARMA_DE_FOGO">ARMA DE FOGO</option>
                <option value="ARMA_BRANCA">ARMA BRANCA</option>
                <option value="SIMULACRO">SIMULACRO</option>
            </select>

            <label for="id_especie_arma">Especie arma:</label>
            <input class="form-control" type="text" name="especie_arma" maxlength="50"  id="id_especie_arma">

            <label for="id_qtd_arma">Qtd arma:</label>
            <input class="form-control" type="number" name="qtd_arma"  id="id_qtd_arma">
        </div>
        <span class="mt-4 fs-5">Munição:</span> 
        <div class="form-control m-auto">
            <label for="id_municao">Quantidade de Munição:</label>
            <input class="form-control" type="number" name="municao"  id="id_municao">
        </div>
        <span class="mt-4 fs-5">Celular:</span> 
        <div class="form-control m-auto">
            <label for="id_imei1_celular">Imei1 celular:</label>
            <input class="form-control" type="text" name="imei1_celular" maxlength="50"  id="id_imei1_celular">

            <label for="id_imei2_celular">Imei2 celular:</label>
            <input class="form-control" type="text" name="imei2_celular" maxlength="50"  id="id_imei2_celular">
        </div>
        <span class="mt-4 fs-5">Outros objetos:</span> 
        <div class="form-control m-auto">
            <label for="id_outros_objetos">Outros objetos:</label>
            <input class="form-control" type="text" name="outros_objetos" maxlength="200"  id="id_outros_objetos">

            <label for="id_qtd_outros_objetos">Qtd outros objetos:</label>
            <input class="form-control" type="number" name="qtd_outros_objetos"  id="id_qtd_outros_objetos">
        </div>
        <span class="mt-4 fs-5">Veículo:</span> 
        <div class="form-control m-auto">
            <label for="id_placa_veiculo">Placa veiculo:</label>
            <input class="form-control" type="text" name="placa_veiculo" maxlength="20"  id="id_placa_veiculo">
        </div>
    </div>
</div>